### ISSUE TITLE
Channel monitor agent throws exceptions upon microservices shutdown

### ISSUE THREAD

**Issue by vso-tc** [tcdl/msb-java#293]
The monitor throws exception upon microservice shutdown

```
15:43:17,122 ERROR [AMQP Connection 127.0.0.1:5672] AmqpAutoRecoveringChannel - Shutdown is NOT initiated by application. Resetting the channel.
com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange '_channels:heartbeat' in vhost '/', class-id=60, method-id=40)
    at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:478)
    at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:315)
    at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:144)
    at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:91)
    at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:552)
    at java.lang.Thread.run(Thread.java:745)
```

Steps to reproduce:
1. Start `io.github.tcdl.msb.examples.Monitor`
2. Start `io.github.tcdl.msb.examples.DateExtractor`
3. Observe monitor logging heartbeat to console (as intended)
4. Stop the microservice
5. Observe abovementioned error in monitor console (not intended)

**Comment by rkatsyuryna** [comment]
cause of that is: Exchanges which are declared as auto-delete=true will be removed when all their bindings are removed.  Changed declared exchanges to auto-delete=false

**Comment by rkatsyuryna** [comment]
Fixed for msb-java. Please not close this until changes for msb will not be duplicated. See https://github.com/tcdl/msb/issues/64
